// Sync engine — local-first replication of engagement data between a client mirror and
// the team server. Both sides run the SAME code over the SAME schema; only the transport
// differs (the client pulls/pushes over HTTPS, the server answers).
//
// Model (agreed with the user): row-level LAST-WRITER-WINS by a logical clock.
//   - Every syncable row carries a global `uid` (so the same thing has one identity across
//     machines) and an `hlc` stamp "<ms>-<seq>-<node>" that sorts by time, then per-node
//     sequence, then node id. Newest hlc wins.
//   - Inserts are additive (two people adding findings never collide). Scalar edits (status,
//     answer, finding body) take the newest hlc. Deletes travel as tombstones and win only
//     if newer than the row.
//   - uids are generated by whoever creates the row, so a client-created finding keeps its
//     identity when it reaches the server — no id remapping.
//
// Capture is by trigger, so no write path in the app has to know about sync and none can
// bypass it. During apply the triggers are muted so incoming hlc/uid are stored verbatim.

// table -> { parents: { fkColumn: parentTable }, cols: [...plain columns...], blobs: [...] }
// Order matters: parents are applied before children.
export const SPEC = {
  projects: { parents: {}, cols: ['name', 'client', 'scope', 'notes', 'status', 'start_date', 'end_date', 'created_at'] },
  folders: { parents: { project_id: 'projects' }, cols: ['grp', 'label', 'created_at'] },
  assets: { parents: { project_id: 'projects', folder_id: 'folders' }, cols: ['type', 'label', 'metadata', 'created_at'] },
  items: {
    parents: { asset_id: 'assets', parent_id: 'items' },
    cols: ['group_key', 'group_title', 'title', 'detail', 'payloads', 'kind', 'spawns', 'catalog', 'options', 'opt_key', 'status', 'answer', 'sort', 'is_custom', 'created_at'],
  },
  findings: { parents: { asset_id: 'assets' }, cols: ['title', 'kind', 'severity', 'body', 'refs', 'fix_status', 'created_at'] },
  attachments: { parents: { finding_id: 'findings' }, cols: ['filename', 'mime', 'size', 'created_at'], blobs: ['data'] },
};
const TABLES = Object.keys(SPEC);

// Physical wall-clock milliseconds, as SQLite computes them ('now' is constant within a
// single statement, so the two references below always agree).
const MS = `CAST((julianday('now')-2440587.5)*86400000 AS INTEGER)`;
// Advance the hybrid logical clock. Two guarantees: the leading field never moves backwards
// (so a clock step-back can't make a newer edit lose), and `seq` resets whenever the ms
// advances (so it stays a tiny number and can never overflow its %06d field after ~1M writes).
const BUMP = `UPDATE _sync_meta SET
  seq = CASE WHEN ${MS} > last_ms THEN 0 ELSE seq + 1 END,
  last_ms = MAX(${MS}, last_ms)
  WHERE k='main';`;
// The stamp, sortable as a plain string: "<logical-ms>-<seq>-<node>". Newest wins.
const HLC = `printf('%015d-%06d-%s',
  (SELECT last_ms FROM _sync_meta WHERE k='main'),
  (SELECT seq FROM _sync_meta WHERE k='main'),
  (SELECT node FROM _sync_meta WHERE k='main'))`;

/** Install sync columns, bookkeeping tables and capture triggers. Idempotent. */
export function setupSchema(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS _sync_meta (k TEXT PRIMARY KEY, node TEXT, seq INTEGER NOT NULL DEFAULT 0,
      last_ms INTEGER NOT NULL DEFAULT 0, pull_wm TEXT NOT NULL DEFAULT '', push_wm TEXT NOT NULL DEFAULT '');
    CREATE TABLE IF NOT EXISTS _sync_mute (x INTEGER);
    CREATE TABLE IF NOT EXISTS tombstones (tbl TEXT NOT NULL, uid TEXT NOT NULL, hlc TEXT NOT NULL, PRIMARY KEY (tbl, uid));
    -- Personal engagements set aside on connect. Kept IN the database (not a file) so the
    -- export and the delete of those projects are one atomic transaction — a crash can never
    -- lose them or leave the two out of step. Never synced (not a SPEC table). failed=1 marks
    -- a stash that could not be fully re-imported, so it is preserved but not auto-restored.
    CREATE TABLE IF NOT EXISTS stash_blobs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      failed INTEGER NOT NULL DEFAULT 0,
      data TEXT NOT NULL);
  `);
  // A mute is only ever meant to bracket one in-process call. If a crash left one behind it
  // would silently freeze all change capture forever, so clear any leftover on every boot.
  db.exec(`DELETE FROM _sync_mute`);
  // _sync_meta gained last_ms after the first release (the hybrid clock).
  if (!new Set(db.prepare(`PRAGMA table_info(_sync_meta)`).all().map(r => r.name)).has('last_ms'))
    db.exec(`ALTER TABLE _sync_meta ADD COLUMN last_ms INTEGER NOT NULL DEFAULT 0`);
  if (!db.prepare(`SELECT 1 FROM _sync_meta WHERE k='main'`).get()) {
    db.prepare(`INSERT INTO _sync_meta (k, node, seq) VALUES ('main', lower(hex(randomblob(8))), 0)`).run();
  }
  for (const t of TABLES) {
    const cols = new Set(db.prepare(`PRAGMA table_info(${t})`).all().map(r => r.name));
    if (!cols.has('uid')) db.exec(`ALTER TABLE ${t} ADD COLUMN uid TEXT`);
    if (!cols.has('hlc')) db.exec(`ALTER TABLE ${t} ADD COLUMN hlc TEXT`);
    db.exec(`CREATE INDEX IF NOT EXISTS idx_${t}_uid ON ${t}(uid)`);
    db.exec(`CREATE INDEX IF NOT EXISTS idx_${t}_hlc ON ${t}(hlc)`);
    // Drop-then-create so an upgrade replaces the older trigger bodies (CREATE IF NOT EXISTS
    // would keep the old ones). Triggers are stateless, so this is safe.
    // INSERT: assign a uid if none was supplied, stamp the clock.
    db.exec(`DROP TRIGGER IF EXISTS ${t}__ai;
      CREATE TRIGGER ${t}__ai AFTER INSERT ON ${t}
      WHEN NOT EXISTS (SELECT 1 FROM _sync_mute) BEGIN
        ${BUMP}
        UPDATE ${t} SET uid = COALESCE(uid, lower(hex(randomblob(16)))), hlc = ${HLC} WHERE rowid = NEW.rowid;
      END;`);
    // UPDATE: re-stamp the clock (skip our own hlc-only writes via the mute guard).
    db.exec(`DROP TRIGGER IF EXISTS ${t}__au;
      CREATE TRIGGER ${t}__au AFTER UPDATE ON ${t}
      WHEN NOT EXISTS (SELECT 1 FROM _sync_mute) BEGIN
        ${BUMP}
        UPDATE ${t} SET hlc = ${HLC} WHERE rowid = NEW.rowid;
      END;`);
    // DELETE: leave a tombstone so the removal propagates.
    db.exec(`DROP TRIGGER IF EXISTS ${t}__ad;
      CREATE TRIGGER ${t}__ad AFTER DELETE ON ${t}
      WHEN NOT EXISTS (SELECT 1 FROM _sync_mute) AND OLD.uid IS NOT NULL BEGIN
        ${BUMP}
        INSERT INTO tombstones (tbl, uid, hlc) VALUES ('${t}', OLD.uid, ${HLC})
          ON CONFLICT(tbl, uid) DO UPDATE SET hlc = excluded.hlc;
      END;`);
  }
  backfill(db);
}

// Give rows that predate sync (or arrived via import) a uid and an initial clock, so they
// are pushed on the first sync. One UPDATE per table: it assigns a uid where missing, and
// the AFTER UPDATE trigger stamps each touched row's clock. `randomblob()` is evaluated
// per row, so every row gets a distinct uid. Idempotent — a second run matches nothing.
//
// (An earlier version did `SELECT rowid … WHERE uid IS NULL` then bound r.rowid, but on an
// INTEGER PRIMARY KEY table that column comes back named `id`, so r.rowid was undefined and
// the bind threw. Only a pre-sync database has null-uid rows, which is why tests missed it.)
function backfill(db) {
  for (const t of TABLES) {
    db.exec(`UPDATE ${t} SET uid = COALESCE(uid, lower(hex(randomblob(16)))) WHERE uid IS NULL OR hlc IS NULL`);
  }
}

// Run fn with capture triggers muted — used for local-only moves (stash/restore) that must
// not turn into tombstones or clock bumps. Non-transactional so callers that open their own
// transaction (e.g. importProject) still work.
export function mutedRun(db, fn) {
  db.prepare(`INSERT INTO _sync_mute (x) VALUES (1)`).run();
  try { return fn(); }
  finally { db.prepare(`DELETE FROM _sync_mute`).run(); }
}

export function node(db) { return db.prepare(`SELECT node FROM _sync_meta WHERE k='main'`).get().node; }
export function watermarks(db) {
  const m = db.prepare(`SELECT pull_wm, push_wm FROM _sync_meta WHERE k='main'`).get();
  return { pull: m.pull_wm || '', push: m.push_wm || '' };
}
export function setWatermarks(db, { pull, push }) {
  if (pull !== undefined) db.prepare(`UPDATE _sync_meta SET pull_wm=? WHERE k='main'`).run(pull);
  if (push !== undefined) db.prepare(`UPDATE _sync_meta SET push_wm=? WHERE k='main'`).run(push);
}

const uidOf = (db, table, id) => (id == null ? null : db.prepare(`SELECT uid FROM ${table} WHERE id=?`).get(id)?.uid || null);
const idOf = (db, table, uid) => (uid == null ? null : db.prepare(`SELECT id FROM ${table} WHERE uid=?`).get(uid)?.id ?? null);

/**
 * Collect all changes with hlc greater than `since`.
 * @param onlyLocal when true, only rows this node authored (for a client push).
 */
export function collectChanges(db, since = '', { onlyLocal = false } = {}) {
  const rows = [];
  const nd = node(db);
  for (const t of TABLES) {
    const spec = SPEC[t];
    const sel = ['id', 'uid', 'hlc', ...spec.cols, ...(spec.blobs || []), ...Object.keys(spec.parents)];
    let sql = `SELECT ${sel.join(',')} FROM ${t} WHERE hlc > ? AND uid IS NOT NULL`;
    const args = [since];
    if (onlyLocal) { sql += ` AND hlc LIKE ?`; args.push('%-' + nd); }
    for (const r of db.prepare(sql).all(...args)) {
      const fields = {};
      for (const c of spec.cols) fields[c] = r[c];
      for (const b of (spec.blobs || [])) fields[b] = r[b] == null ? null : Buffer.from(r[b]).toString('base64');
      const parents = {};
      for (const [fk, pt] of Object.entries(spec.parents)) parents[fk] = uidOf(db, pt, r[fk]);
      rows.push({ table: t, uid: r.uid, hlc: r.hlc, fields, parents });
    }
  }
  let ts = `SELECT tbl, uid, hlc FROM tombstones WHERE hlc > ?`;
  const targs = [since];
  if (onlyLocal) { ts += ` AND hlc LIKE ?`; targs.push('%-' + nd); }
  const tombstones = db.prepare(ts).all(...targs);
  return { rows, tombstones };
}

/**
 * Merge a payload into this database with last-writer-wins, muting capture triggers so the
 * incoming hlc/uid are stored verbatim. Returns counts. Runs in one transaction.
 */
export function applyChanges(db, { rows = [], tombstones = [] } = {}) {
  // One ordered stream: apply oldest-first so a later delete beats an earlier create, etc.
  const ops = [
    ...rows.map(r => ({ kind: 'row', hlc: r.hlc, r })),
    ...tombstones.map(t => ({ kind: 'tomb', hlc: t.hlc, t })),
  ].sort((a, b) => (a.hlc < b.hlc ? -1 : a.hlc > b.hlc ? 1 : 0));

  let applied = 0, deleted = 0;
  db.prepare('BEGIN').run();
  db.prepare(`INSERT INTO _sync_mute (x) VALUES (1)`).run();
  try {
    let pending = ops, lastPending = -1;
    // Fixpoint: inserts whose parent row hasn't arrived yet are retried once the parent lands.
    while (pending.length && pending.length !== lastPending) {
      lastPending = pending.length;
      const still = [];
      for (const op of pending) {
        if (op.kind === 'tomb') { if (applyTomb(db, op.t)) deleted++; continue; }
        const res = applyRow(db, op.r);
        if (res === 'defer') still.push(op);
        else if (res) applied++;
      }
      pending = still;
    }
    db.prepare(`DELETE FROM _sync_mute`).run();
    db.prepare('COMMIT').run();
    // Report the rows we could not place (parent absent) so the caller does not advance its
    // watermark past them and lose them — they must be re-sent on a later cycle.
    return { applied, deleted, deferred: pending.filter(o => o.kind === 'row').map(o => ({ table: o.r.table, uid: o.r.uid, hlc: o.r.hlc })) };
  } catch (e) {
    db.prepare(`DELETE FROM _sync_mute`).run();
    db.prepare('ROLLBACK').run();
    throw e;
  }
}

function applyRow(db, r) {
  const spec = SPEC[r.table];
  if (!spec) return false; // unknown table name from a peer — never interpolate it into SQL
  // Resolve parent uids -> local ids; a missing parent means "try again after it arrives".
  const fkVals = {};
  for (const [fk, pt] of Object.entries(spec.parents)) {
    const puid = r.parents?.[fk];
    if (puid == null) { fkVals[fk] = null; continue; }
    const pid = idOf(db, pt, puid);
    if (pid == null) return 'defer';
    fkVals[fk] = pid;
  }
  const cur = db.prepare(`SELECT id, hlc FROM ${r.table} WHERE uid=?`).get(r.uid);
  if (cur && !(r.hlc > cur.hlc)) return false; // local copy is newer or equal — keep it

  const colVals = {};
  for (const c of spec.cols) colVals[c] = r.fields?.[c] ?? null;
  for (const b of (spec.blobs || [])) colVals[b] = r.fields?.[b] == null ? null : Buffer.from(r.fields[b], 'base64');

  const cols = [...spec.cols, ...(spec.blobs || []), ...Object.keys(spec.parents)];
  const all = { ...colVals, ...fkVals };
  if (!cur) {
    const names = ['uid', 'hlc', ...cols];
    db.prepare(`INSERT INTO ${r.table} (${names.join(',')}) VALUES (${names.map(() => '?').join(',')})`)
      .run(r.uid, r.hlc, ...cols.map(c => all[c]));
  } else {
    db.prepare(`UPDATE ${r.table} SET hlc=?, ${cols.map(c => c + '=?').join(', ')} WHERE uid=?`)
      .run(r.hlc, ...cols.map(c => all[c]), r.uid);
  }
  return true;
}

function applyTomb(db, t) {
  if (!SPEC[t.tbl]) return false; // reject an unknown table before it reaches interpolated SQL
  db.prepare(`INSERT INTO tombstones (tbl, uid, hlc) VALUES (?,?,?)
    ON CONFLICT(tbl, uid) DO UPDATE SET hlc=excluded.hlc WHERE excluded.hlc > tombstones.hlc`).run(t.tbl, t.uid, t.hlc);
  const cur = db.prepare(`SELECT hlc FROM ${t.tbl} WHERE uid=?`).get(t.uid);
  if (cur && t.hlc > cur.hlc) { db.prepare(`DELETE FROM ${t.tbl} WHERE uid=?`).run(t.uid); return true; }
  return false;
}

/** Highest hlc present anywhere — the watermark to remember after a successful exchange. */
export function maxHlc(db, ...extra) {
  let m = '';
  for (const t of TABLES) { const v = db.prepare(`SELECT MAX(hlc) h FROM ${t}`).get().h; if (v && v > m) m = v; }
  const tv = db.prepare(`SELECT MAX(hlc) h FROM tombstones`).get().h; if (tv && tv > m) m = tv;
  for (const v of extra) if (v && v > m) m = v;
  return m;
}
